
export type Language = 'fr' | 'en' | 'es' | 'ar';

export const translations = {
  fr: {
    nav: { home: 'Accueil', about: 'À propos', academic: 'Parcours', experience: 'Expérience', skills: 'Compétences', contact: 'Contact', button: 'Me contacter' },
    hero: { badge: 'Étudiant BUT MTEE 1ère Année', intro: "Engagé pour la transition énergétique. Je construis mon parcours vers l'ingénierie des énergies renouvelables pour relever les défis de demain.", contact: 'Me contacter', cv: 'Télécharger mon CV', focus: 'Focus Actuel', energy: 'Efficacité Énergétique' },
    about: { title: 'Profil', heading: "L'énergie de demain s'écrit avec audace.", body: "Plus qu'un simple étudiant, je suis un explorateur de solutions techniques. Mon approche est guidée par la fusion entre la rigueur mathématique et une créativité sans bornes.", vision_title: 'Mon Approche', vision_text: "Je ne me contente pas de comprendre les systèmes, je cherche à les réinventer pour qu'ils soient plus économes, plus fluides et plus humains.", mindset_title: 'Mes Valeurs', mindset_text: "Esprit d'équipe, autonomie totale et une curiosité insatiable. Je crois que le progrès nait de la collaboration et de la remise en question perpétuelle.", banner1: "En route pour l'ingénierie énergétique", banner2: 'Acteur de la transition durable', banner_btn: 'Découvrir mon projet' },
    academic: { title: 'Parcours académique', heading: 'Formation & Diplômes', current: 'En cours', mtee_title: 'BUT MTEE', mtee_school: 'IUT - 1ère Année', mtee_desc: "Formation technique axée sur la production, la distribution et la gestion de l'énergie. Étude de la thermique, thermodynamique et des systèmes renouvelables.", bac_title: 'Baccalauréat Général', bac_school: 'Spécialités : Mathématiques & Physique-Chimie', bac_desc: 'Solide socle scientifique préparant aux études supérieures en ingénierie.' },
    experience: { title: 'Parcours Professionnel', heading: "L'école de la responsabilité sur le terrain.", text: "Chaque mission en centre de loisirs a forgé les bases de mon management et de mon organisation.", role: 'Animateur', company: 'Centre de Loisirs', impact: 'Confiance & Adaptabilité', mission1: 'Création et animation', mission1_desc: "Conception d'activités pédagogiques innovantes pour favoriser l'éveil et l'apprentissage ludique des enfants.", mission2: 'Gestion organisationnelle', mission2_desc: "Optimisation et suivi des emplois du temps pour assurer une fluidité dans le déroulement des journées.", mission3: 'Communication & Accueil', mission3_desc: "Interface privilégiée avec les parents pour assurer un suivi sécurisant et professionnel." },
    skills: { title: 'Compétences', heading: 'Expertise & Savoir-être', soft: 'Soft Skills', technical: 'Expertise Technique', creative: 'Créatif', team: "Esprit d'équipe", autonomous: 'Autonome', thermal: 'Thermique & Fluides', maths: 'Mathématiques', physics: 'Physique Appliquée' },
    interests: { title: "Centres d'intérêt", heading: 'Mon Équilibre Personnel', sport: 'Sport', travel: 'Voyages', languages: 'Langues', tag1: 'Dépassement', tag2: 'Découverte', tag3: 'Communication' },
    project: { title: 'Projet professionnel', heading: 'Objectif : Ingénierie en énergies renouvelables', intro: "Après mon BUT MTEE, je projette d'intégrer une école d'ingénieur pour me spécialiser dans la conception de systèmes énergétiques durables. Mon ambition est de participer activement à la décarbonation de notre industrie et de nos territoires.", short_title: 'Vision Court Terme', short_desc: "Maîtriser les fondamentaux techniques du génie climatique et de l'efficacité énergétique au sein du BUT MTEE.", long_title: 'Vision Long Terme', long_desc: "Devenir un acteur clé de la transition énergétique en tant qu'ingénieur, pilotant des projets d'innovation durable." },
    contact: { title: 'Contact', heading: 'Discutons de vos projets et de mon profil.', text: 'Je suis ouvert aux échanges concernant des stages, des projets collaboratifs ou simplement pour partager sur la transition énergétique.', email: 'Email', loc: 'Localisation', loc_val: 'France, IUT MTEE', name_label: 'Nom Complet', email_label: 'Email', msg_label: 'Message', send: 'Envoyer le message' }
  },
  en: {
    nav: { home: 'Home', about: 'About', academic: 'Education', experience: 'Experience', skills: 'Skills', contact: 'Contact', button: 'Contact Me' },
    hero: { badge: '1st Year BUT MTEE Student', intro: "Committed to the energy transition. I am building my path towards renewable energy engineering to meet tomorrow's challenges.", contact: 'Contact Me', cv: 'Download CV', focus: 'Current Focus', energy: 'Energy Efficiency' },
    about: { title: 'Profile', heading: 'Tomorrow’s energy is written with boldness.', body: "More than just a student, I am an explorer of technical solutions. My approach is guided by the fusion of mathematical rigor and boundless creativity.", vision_title: 'My Approach', vision_text: "I don't just understand systems; I seek to reinvent them to be more efficient, smoother, and more human.", mindset_title: 'My Values', mindset_text: "Team spirit, total autonomy, and an insatiable curiosity. I believe progress is born from collaboration and constant questioning.", banner1: 'Heading for energy engineering', banner2: 'Actor of sustainable transition', banner_btn: 'Discover my project' },
    academic: { title: 'Academic Career', heading: 'Education & Diplomas', current: 'Ongoing', mtee_title: 'BUT MTEE', mtee_school: 'IUT - 1st Year', mtee_desc: 'Technical training focused on energy production, distribution, and management. Study of thermal dynamics and renewable systems.', bac_title: 'General Baccalaureate', bac_school: 'Specialties: Mathematics & Physics-Chemistry', bac_desc: 'Solid scientific foundation preparing for higher engineering studies.' },
    experience: { title: 'Professional Path', heading: 'The school of responsibility in the field.', text: 'Each mission in the recreation center has forged the foundations of my management and organization.', role: 'Recreation Leader', company: 'Youth Center', impact: 'Confidence & Adaptability', mission1: 'Creation & Animation', mission1_desc: 'Designing innovative educational activities to foster children’s development and playful learning.', mission2: 'Organizational Management', mission2_desc: 'Optimization and monitoring of schedules to ensure fluid daily operations.', mission3: 'Communication & Welcome', mission3_desc: 'Privileged interface with parents to ensure secure and professional follow-up.' },
    skills: { title: 'Skills', heading: 'Expertise & Soft Skills', soft: 'Soft Skills', technical: 'Technical Expertise', creative: 'Creative', team: 'Team Spirit', autonomous: 'Autonomous', thermal: 'Thermal & Fluids', maths: 'Mathematics', physics: 'Applied Physics' },
    interests: { title: 'Interests', heading: 'My Personal Balance', sport: 'Sport', travel: 'Travel', languages: 'Languages', tag1: 'Challenge', tag2: 'Discovery', tag3: 'Communication' },
    project: { title: 'Professional Project', heading: 'Goal: Renewable Energy Engineering', intro: 'After my BUT MTEE, I plan to join an engineering school to specialize in the design of sustainable energy systems. My ambition is to actively participate in the decarbonization of our industry.', short_title: 'Short Term Vision', short_desc: 'Master the technical fundamentals of climate engineering and energy efficiency within the BUT MTEE.', long_title: 'Long Term Vision', long_desc: 'Become a key player in the energy transition as an engineer, leading sustainable innovation projects.' },
    contact: { title: 'Contact', heading: "Let's discuss your projects and my profile.", text: 'I am open to discussions regarding internships, collaborative projects, or simply to share views on the energy transition.', email: 'Email', loc: 'Location', loc_val: 'France, IUT MTEE', name_label: 'Full Name', email_label: 'Email', msg_label: 'Message', send: 'Send Message' }
  },
  es: {
    nav: { home: 'Inicio', about: 'Sobre mí', academic: 'Formación', experience: 'Experiencia', skills: 'Habilidades', contact: 'Contacto', button: 'Contáctame' },
    hero: { badge: 'Estudiante de 1er año BUT MTEE', intro: 'Comprometido con la transición energética. Construyo mi camino hacia la ingeniería de energías renovables.', contact: 'Contáctame', cv: 'Descargar CV', focus: 'Enfoque Actual', energy: 'Eficiencia Energética' },
    about: { title: 'Perfil', heading: 'La energía del mañana se escribe con audacia.', body: 'Más que un estudiante, soy un explorador de soluciones técnicas guiado por el rigor matemático y la creatividad.', vision_title: 'Mi Enfoque', vision_text: 'Busco reinventar los sistemas para que sean más eficientes, fluidos y humanos.', mindset_title: 'Mis Valores', mindset_text: 'Espíritu de equipo, autonomía y curiosidad insaciable.', banner1: 'Rumbo a la ingeniería energética', banner2: 'Actor de la transición sostenible', banner_btn: 'Descubre mi proyecto' },
    academic: { title: 'Carrera Académica', heading: 'Formación y Títulos', current: 'En curso', mtee_title: 'BUT MTEE', mtee_school: 'IUT - 1er Año', mtee_desc: 'Formación técnica en producción, distribución y gestión de energía.' },
    experience: { title: 'Trayectoria Profesional', heading: 'La escuela de la responsabilidad en el campo.', text: 'Cada misión ha forjado las bases de mi gestión y organización.', role: 'Monitor de Ocio', company: 'Centro Juvenil', impact: 'Confianza y Adaptabilidad', mission1: 'Creación y Animación', mission1_desc: 'Diseño de actividades educativas innovadoras.', mission2: 'Gestión Organizativa', mission2_desc: 'Optimización de horarios.', mission3: 'Comunicación', mission3_desc: 'Relación profesional con las familias.' },
    skills: { title: 'Habilidades', heading: 'Experiencia y Aptitudes', soft: 'Soft Skills', technical: 'Experiencia Técnica', creative: 'Creativo', team: 'Espíritu de equipo', autonomous: 'Autónomo', thermal: 'Térmica y Fluidos', maths: 'Matemáticas', physics: 'Física Aplicada' },
    interests: { title: 'Intereses', heading: 'Mi Equilibrio Personal', sport: 'Deporte', travel: 'Viajes', languages: 'Idiomas', tag1: 'Superación', tag2: 'Descubrimiento', tag3: 'Comunicación' },
    project: { title: 'Proyecto Profesional', heading: 'Objetivo: Ingeniería en Energías Renovables', intro: 'Mi ambición es participar activamente en la descarbonización de la industria.', short_title: 'Visión Corto Plazo', short_desc: 'Dominar los fundamentos técnicos de la ingeniería climática.', long_title: 'Visión Largo Plazo', long_desc: 'Convertirme en un actor clave de la transición energética.' },
    contact: { title: 'Contacto', heading: 'Hablemos de tus proyectos.', text: 'Abierto a intercambios sobre prácticas y proyectos.', email: 'Correo', loc: 'Ubicación', loc_val: 'Francia, IUT MTEE', name_label: 'Nombre Completo', email_label: 'Email', msg_label: 'Mensaje', send: 'Enviar mensaje' }
  },
  ar: {
    nav: { home: 'الرئيسية', about: 'عني', academic: 'المسار', experience: 'الخبرة', skills: 'المهارات', contact: 'اتصل بي', button: 'اتصل بي' },
    hero: { badge: 'طالب سنة أولى BUT MTEE', intro: 'ملتزم بالتحول الطاقي. أبني مساري نحو هندسة الطاقات المتجددة لمواجهة تحديات الغد.', contact: 'اتصل بي', cv: 'تحميل السيرة الذاتية', focus: 'التركيز الحالي', energy: 'كفاءة الطاقة' },
    about: { title: 'الملف الشخصي', heading: 'طاقة الغد تُكتب بجرأة.', body: 'أكثر من مجرد طالب، أنا مستكشف للحلول التقنية. نهجي مسترشد بالدقة الرياضية والإبداع اللامحدود.', vision_title: 'نهجي', vision_text: 'أسعى لإعادة ابتكار الأنظمة لتكون أكثر كفاءة وسلاسة وإنسانية.', mindset_title: 'قيمي', mindset_text: 'روح الفريق، الاستقلالية التامة، والفضول الذي لا يشبع.', banner1: 'في الطريق إلى هندسة الطاقة', banner2: 'فاعل في التحول المستدام', banner_btn: 'اكتشف مشروعي' },
    academic: { title: 'المسار الأكاديمي', heading: 'التكوين والشهادات', current: 'جاري', mtee_title: 'BUT MTEE', mtee_school: 'IUT - السنة الأولى', mtee_desc: 'تكوين تقني يركز على إنتاج وتوزيع وإدارة الطاقة.' },
    experience: { title: 'المسار المهني', heading: 'مدرسة المسؤولية في الميدان.', text: 'كل مهمة في مركز الترفيه صقلت أسس الإدارة والتنظيم لدي.', role: 'منشط', company: 'مركز ترفيهي', impact: 'الثقة والتكيف', mission1: 'الابتكار والتنشيط', mission1_desc: 'تصميم أنشطة تربوية مبتكرة لتعزيز تعلم الأطفال.', mission2: 'الإدارة التنظيمية', mission2_desc: 'تحسين ومتابعة الجداول الزمنية لضمان سلاسة العمل.', mission3: 'التواصل والاستقبال', mission3_desc: 'واجهة متميزة مع أولياء الأمور لضمان متابعة مهنية.' },
    skills: { title: 'المهارات', heading: 'الخبرة والمهارات الشخصية', soft: 'مهارات ناعمة', technical: 'خبرة تقنية', creative: 'مبدع', team: 'روح الفريق', autonomous: 'مستقل', thermal: 'الحرارة والسوائل', maths: 'الرياضيات', physics: 'الفيزياء التطبيقية' },
    interests: { title: 'الاهتمامات', heading: 'توازني الشخصي', sport: 'الرياضة', travel: 'السفر', languages: 'اللغات', tag1: 'تحدي', tag2: 'اكتشاف', tag3: 'تواصل' },
    project: { title: 'المشروع المهني', heading: 'الهدف: هندسة الطاقات المتجددة', intro: 'أطمح للمشاركة بفعالية في إزالة الكربون من صناعتنا.', short_title: 'رؤية قصيرة المدى', short_desc: 'إتقان الأساسيات التقنية للهندسة المناخية وكفاءة الطاقة.', long_title: 'رؤية طويلة المدى', long_desc: 'أن أصبح فاعلاً رئيسياً في التحول الطاقي كمهندس.' },
    contact: { title: 'اتصال', heading: 'دعونا نناقش مشاريعكم وملفي الشخصي.', text: 'أنا منفتح على التبادلات بخصوص التدريب أو المشاريع التعاونية.', email: 'البريد الإلكتروني', loc: 'الموقع', loc_val: 'فرنسا، IUT MTEE', name_label: 'الاسم الكامل', email_label: 'البريد الإلكتروني', msg_label: 'الرسالة', send: 'إرسال الرسالة' }
  }
};
